### ISSUE TITLE
changing conf.yaml requires new deploy \ new bundle

### ISSUE THREAD

**Issue by drorbar** [tanaylab/MCView#38]
As it sounds, if we change something in the configuration we are required to redeploy everything 
tested on mc1 

btw - having a conf page in mcview might be nice way to change those things

**Comment by aviezerl** [comment]
I think this might be due to the server you are deploying to. `shiny-server` has it's own cache so you might have to restart it to see the configuration changes. 

Also - it is important to remember to update the configuration in config.yaml file which is inside the bundle folder (and not the original one). 

Aviezer
